function bar(){
	ev["bar_guild"]={
		ev:function(){
			show("在收了一笔可观的小费后，酒吧老板小声说道：")
			show("公会会长和教官曾经是恋人。",true)
			show("由于会长多次在冒险中被魔物强奸，她的身体无法再被教官满足。两个人就此分手。")
			show("据说，教官在那之后苦练床技，立誓要让每个他教过的女冒险者用身体记住人类男性的好处。")
			show("你从未听说过如此离奇……不对，是离谱的爱情故事。")
		},
		town:true,
		once:true,
		chance:function(){
			if(past_event.includes("guild_trainer"))return 0.02
		},
	}
	ev["bar_guild2"]={
		ev:function(){
			show("在收了一笔可观的小费后，酒吧老板小声说道：")
			show("公会会长是一个分得清工作和生活的人。",true)
			show("见你没有听明白，他用更小的声音补充道：讨伐魔物是工作，输给魔物才是生活。")
		},
		town:true,
		once:true,
		chance:function(){
			if(past_event.includes("guild_leader"))return 0.02
		}
	}
	ev["bar_goblin"]={
		ev:function(){
			show("在收了一笔可观的小费后，酒吧老板小声说道：")
			show("哥布林法师施法的效果不太稳定。但只要你多遇见它几次，总会有发生意外的时候。")
			show("别把它手里的法杖当成是木棍——顺便一提，有时候哥布林法师自己就会拿法杖当木棍用。")
			show("见你没有听明白，他补充道：上面那句是冷笑话。")
		},
		town:true,
		once:true,
		chance:function(){
			return 0.1
		},
		start:1,
		end:1
	}
	ev["bar_slime"]={
		ev:function(){
			show("在收了一笔可观的小费后，酒吧老板小声说道：")
			show("人类生下的史莱姆有概率会继承母体的外表和技能。")
		},
		town:true,
		once:true,
		chance:function(){
			return 0.1
		},
		start:2,
		end:2
	}
	ev["bar_orc"]={
		ev:function(){
			show("在收了一笔可观的小费后，酒吧老板小声说道：")
			show("兽人是一个重视荣誉的种族。")
			show("问题是，他们将公开强奸视为一种荣誉。")
		},
		town:true,
		once:true,
		chance:function(){
			return 0.1
		},
		start:3,
		end:3
	}
	ev["bar_tentacle"]={
		ev:function(){
			show("在收了一笔可观的小费后，酒吧老板小声说道：")
			show("一些幼体触手在胎内时就会对母体释放魔力，让她对触手产生母性本能。")
			show("每年都有产下触手的女冒险者造成或大或小的事故。")
		},
		town:true,
		once:true,
		chance:function(){
			return 0.1
		},
		start:4,
		end:4
	}
	ev["bar_boss"]={
		ev:function(){
			show("在收了一笔可观的小费后，酒吧老板小声说道：")
			show("众所周知，四大天王对应着四种攻击属性。")
			show("见你没有听明白，他补充道：力量，智力和敏捷加起来是三种属性，但攻击属性确实有四种。")
		},
		town:true,
		once:true,
		chance:function(){
			return 0.1
		},
		start:5,
		end:5
	}
}