let succubus_pow=35
let succubus_m=80
let succubus_e=40
function finalboss(){
	ev["succubus"]={
		ev:function(){
			show("你被魅魔从后方偷袭了。")
			if(rand(2)==0){
				show("她一边玩弄着你的胸部，一边在你的耳边低语着。")
				if(check("str",succubus_pow-5+status.b_lv)>=0){
					show("你挣脱了她的控制。")
					gain({money:succubus_m,exp:succubus_e,b_exp:1,les_exp:1})
				}else{
					show("你沉迷于快感，没有挣脱。")
					gain({b_exp:5,les_exp:5})
				}
			}else{
				show("她一边玩弄着你的蜜裂，一边在你的耳边低语着。")
				if(check("str",30+status.v_lv)>=0){
					show("你挣脱了她的控制。")
					gain({money:50,exp:20,v_exp:1,les_exp:1})
				}else{
					show("你沉迷于快感，没有挣脱。")
					gain({v_exp:5,les_exp:5})
				}
			}
		},
		town:false,
		chance:function(){
			return 1
		},
		start:5,
		end:5
	}

	ev["succubus2"]={
		ev:function(){
			show("魅魔对你释放了魅惑魔法。")
			if(check("wis",succubus_pow-5+status.m_lv)>=0){
				show("你抵抗住了诱惑。")
				gain({money:succubus_m,exp:succubus_e})
			}else{
				show("你按照魅魔的指示开始自慰。")
				masturbation(5)
			}
		},
		town:false,
		chance:function(){
			return 1
		},
		start:5,
		end:5
	}

	ev["succubus3"]={
		ev:function(){
			show("魅魔对你释放了催眠魔法。")
			if(check("wis",succubus_pow)>=0){
				show("你没有中招。")
				gain({money:succubus_m,exp:succubus_e})
			}else{
				show("你觉得自己没有中招。")
				gainbuff("催眠")
			}
		},
		town:false,
		chance:function(){
			return 1
		},
		start:5,
		end:5
	}

	ev["succubus4"]={
		ev:function(){
			if(check("dex",status.les_lv+succubus_pow-5)>=0){
				show("你抵抗住诱惑，消灭了一个魅魔。")
				gain({money:succubus_m,exp:succubus_e})
			}else{
				show("你击倒了一个魅魔。")
				show("看着她美丽的外表，你没能下死手，只是让她离开，别再袭击人类。")
				show("魅魔在离开前吻了你。")
				gain({money:50,o_exp:3,les_exp:2},"魅魔")
			}
		},
		town:false,
		chance:function(){
			return 1
		},
		start:5,
		end:5
	}

	ev["succubus_assassin"]={
		ev:function(){
			if(week<=op["刺客"].prison){
				show("你从一个诡异的魔法阵当中救出了刺客，她的下腹部多了一个淫纹。")
				show("刺客感谢了你的帮助。")
				show("你很清楚她接下来会做什么。")
				gain({v_exp:4,a_exp:4,s_exp:2,les_exp:2},"刺客")
				op["刺客"].val+=10000
				gainop("刺客")
				gainbuff("刺客的密友")
			}else{
				show("你遇到了被转化为魅魔的刺客。")
				show("她的肤色变成了暗色，背后多了小巧的翅膀和可爱的尾巴，还有，她的扶她肉棒变得更大了。")
				show("她要求你尽快离开——赶在她控制不住扶她魅魔的本能之前。",true)
				show("")
				show("刺客退出了冒险者公会。")
				if("刺客的密友" in buff){
					gainbuff("刺客的密友",-10000)
				}
			}
		},
		town:false,
		once:true,
		chance:function(){
			if(past_event.includes("assassin5_1")) return 2
		},
		start:5,
		end:5
	}

	ev["succubus3_after"]={
		ev:function(){
			if("触手服"in buff){
				show("当你恢复意识时，你发现自己身上的触手服不见了，除此之外毫无异样。")
				show("你觉得唯一合理的解释就是——魅魔对你身上的触手服的兴趣超过了对你的兴趣。")
				gainbuff("触手服",-10000)
				return
			}
			ans=rand(3)
			if(ans==0){
				show("当你恢复意识时，你正躺在一间男厕里，满身都是精液。")
				gain({v_exp:8,a_exp:4,o_exp:6,s_exp:6,u_exp:2,e_exp:5},"路人")
				gainbuff("公共厕所",1)
			}else if(ans==1){
				show("当你恢复意识时，你正以光着身子，在哥布林的身后爬行。")
				gain({v_exp:5,o_exp:3,p_exp:5,e_exp:5,s_exp:3,u_exp:2},"哥布林")
			}else{
				show("当你恢复意识时，你正在和魔法师共享一根双头假阳具，而武道家骑在刺客的身上扭动身体。")
				gain({v_exp:6,b_exp:3,o_exp:5,les_exp:10,a_exp:3,s_exp:1},"刺客")
			}
			gainbuff("催眠",-10000)
		},
		town:true,
		chance:function(){
			if("催眠"in buff)return 10000
		},
		start:5,
		end:5
	}

	ev["guild_succubus"]={
		ev:function(){
			show("会长召集了公会的成员。")
			show("她宣布魔王要回来了，她感受到了对方的魔力。")
			show("她掀开上衣，展示出自己的小腹。")
			show("那里有着一个心形纹路，散发着微弱的粉色光芒。",true)
			show("会长表示自己当年在讨伐魔王时受到了诅咒，在与魔物交合时能够获得加倍的快感，却无法对人类的身体产生任何反应。")
			show("魔王认为这样就会让她堕落，但她坚持下来了。")
			show("她也会继续坚持下去。")
			op["会长"].prison=week+2
		},
		town:false,
		once:true,
		chance:function(){
			if(week-chapter_startweek>=4) return 2
		},
		start:5,
		end:5
	}

	ev["guild_succubus2"]={
		ev:function(){
			show("你前往公会办理手续时，发现会长只穿着内衣。")
			show("会长表示，这是为了让别人时刻监督自己身上淫纹的恶化程度。")
			gainop("会长")
		},
		town:false,
		once:true,
		chance:function(){
			if(past_event.includes("guild_succubus")&&getop("会长")>=3)
				return 1
		},
		start:5,
		end:5
	}
	ev["guild_succubus3"]={
		ev:function(){
			show("会长召集了公会的成员。")
			show("她宣布自己已经坚持不下去了，然后她身上的淫纹发出了耀眼的光芒。")
			show("当光芒散去时，会长已经变成了魅魔。")
			show("人群一片慌乱。",true)
			show("教官站了出来，表示自己掩护，让你们先撤。")
			show("但会长没有袭击任何人，张开翅膀逃跑了。",true)
			show("会长退出了冒险者公会。")
			op["会长"].val-=10000
			show("",true)

			show("你决定前去讨伐魔王，将会长带回来。")
			if(getop("武道家")>0 && "武道家的战友"in buff){
				show("“这样的大战怎么能少得了我呢？”")
				show("武道家加入了你的队伍。",true)
			}
			if(getop("魔法师")>0 && "魔法师的恋人" in buff){
				show("“不管要面对什么，我都会和姐姐在一起。”")
				show("魔法师加入了你的队伍。",true)
			}
			if(getop("刺客")>0 &&　"刺客的密友" in buff){
				show("“必须终结淫魔的诅咒……”")
				show("刺客加入了你的队伍。",true)
			}
			show("“是时候给过去的恩怨做个了断了。”")
			show("教官加入了你的队伍。",true)
		},
		town:true,
		once:true,
		chance:function(){
			if(week>op["会长"].prison && op["会长"].prison!=null && op["会长"].prison!=0)return week-op["会长"].prison
		},
		start:5,
		end:5
	}
	ev["succubus_boss"]={
		ev:function(){
			show("你踏入了魔王的宫殿。")
			show("一个穿着满是花边的可爱衣服的小女孩等在门后。")
			show("“不要大意！那是前代魔王的女儿！”教官大喊着。")
			show("你反应慢了一步，被她触碰了身体。")
			gainbuff("淫纹")
			var cnt=status.orgasm+50
			show("你注意到自己的下腹部出现了一个心形纹路，上面闪烁着数字50。")
			show("",true)
			show("“只是战斗的话，未免也太无趣了，让我们来玩个游戏吧。”")
			show("“游戏规则很简单——在高潮五十次之后，你就会被转化成魅魔。”")
			show("“不论你是否救出会长，你都会和她再度成为同伴。”魔王自认为讲了一个不错的笑话，怪笑着消失了。",true)
			show("“按照惯例，在挑战我之前，你必须先打倒我手下的四大天王。”魔王不知在何处解说着。")
			show("",true)
			show("口天王出现了。")
			show("“想要通过这里的话，就先吞下我的精液吧！”口天王是一个强壮的兽人，他的肉棒看起来甚至比一般的兽人还要大上几分。",true)
			if(getop("武道家")>=0 && "武道家的战友"in buff){
				show("“就由我来做你的对手！”武道家站了出来，“看看到底是你的存货多，还是我的胃口更大。”")
				show("她一口气吞下了整根兽人肉棒。")
			}else{
				show("你双手握住兽人的巨根，勉强地吞吐着前端。")
				show("兽人对此并不满意，按着你的头一下子就顶到了喉咙的深处。")
				gain({o_exp:20,p_exp:10,s_exp:10},"兽人")
				pause()
				var cnt2=cnt-status.orgasm
				if(cnt2<=0){
					show("淫纹上的数字变成了0。")
					show("你感到子宫内有一种奇妙的感觉。")
					show("你意识到自己无法抗拒，也不必抗拒。")
					show("你躺倒在地，任凭快感传遍全身上下，体内体外的每一个位置。")
					show("粉色的光芒笼罩了你，你抵达了前所未有的强烈高潮。")
					show("当光芒散去时，你成为了魅魔。")
					show("结局：魔王的部下")
					gameover=true
					return
				}else{
					show("淫纹上的数字变成了"+cnt2+"。")
				}
			}
			show("“口天王只是四大天王当中最弱的一个，接下来的三人可没这么好对付。”魔王评论道。")
			show("",true)
			show("乳天王出现了。")
			show("“让你们见识一下，我最伟大的发明——自动榨乳装置3000型！”乳天王是一个老人，在他身边放着一台奇怪的装置。",true)
			if(getop("魔法师")>=0 && "魔法师的恋人" in buff){
				show("“这次该我来保护姐姐了！”魔法师躺到榨乳装置的操作台上，褪去上衣，露出平坦的胸部。")
				show("乳天王对榨乳装置下达指令，但机器似乎扫描不到胸部的存在。")
				show("他反复按下启动键，直到机器发生故障。",true)
				show("“这就是传说中的铁壁防御吗？”魔王评论道。")
			}else{
				if("母乳体质"in buff) {
					show("榨乳装置的吸盘牢牢地吸附在你的胸口。")
					show("强烈的吸力令你的母乳喷涌而出。")
					gain({b_exp:30,p_exp:10})
				}else{
					show("榨乳装置的吸盘牢牢地吸附在你的胸口。")
					show("强烈的吸力将你的胸部吸得生疼。")
					show("见到你没有产出母乳，乳天王按下了一个按钮。")
					show("两针催乳剂被打进了你的乳头，随后，母乳喷涌而出。")
					gain({b_exp:20,p_exp:20})
					gainbuff("母乳体质")
				}
				pause()
				show("")
				var cnt2=cnt-status.orgasm
				if(cnt2<=0){
					show("淫纹上的数字变成了0。")
					show("你感到子宫内有一种奇妙的感觉。")
					show("你意识到自己无法抗拒，也不必抗拒。")
					show("你躺倒在地，任凭快感传遍全身上下，体内体外的每一个位置。")
					show("粉色的光芒笼罩了你，你抵达了前所未有的强烈高潮。")
					show("当光芒散去时，你成为了魅魔。")
					show("结局：魔王的部下")
					gameover=true
					return
				}else{
					show("淫纹上的数字变成了"+cnt2+"。")
				}
				show("“你的乳汁在人类当中称得上美味了。我很期待你成为魅魔后的发挥。”魔王评论道。")
			}
			show("",true)
			show("菊天王出现了。")
			if(rand(20)==0){
				show("“我的鸡鸡可是能够分泌媚药的鸡鸡。”菊天王是一个魅魔，她说话间舔了舔自己的龟头——你没有看错，扶她肉棒的长度就是可以这么离谱。",true)
				show("然后她陷入发情状态，手口胸并用地爱抚着自己的超长肉棒。",true)
				show("你们无视了她，继续前进。")
				show("“这个是小概率出现的彩蛋环节，如果你碰到了，说明你运气很好。”魔王评论道。")
			}else{
				show("“就让姐姐来好好疼爱一下你的菊花吧。”菊天王是一个魅魔，她说话间舔了舔自己的龟头——你没有看错，扶她肉棒的长度就是可以这么离谱。",true)
				if(getop("刺客")>=0 &&　"刺客的密友" in buff){
					show("“在侵犯别人的菊花之前，先担心一下你自己的菊花吧！”刺客不知道何时绕到了她的身后。")
					show("刺客贯穿了魅魔的后庭。魅魔象征性地反抗了两下就不再挣扎，陶醉在被侵犯的快感当中，她的肉棒随着身后的撞击大幅摇晃着。")
				}else{
					show("你被魅魔催眠了。",true)
					show("当你的意识恢复时，你正跨坐在魅魔的腰上，她的肉棒大半没入了你的肛门。")
					show("你挣扎着想要起身，但每次尝试都会刺激到肠壁内侧，令你的身体失去力量再次落下。")
					gain({a_exp:30,p_exp:10,les_exp:10,s_exp:5},"魅魔")
					pause()
					var cnt2=cnt-status.orgasm
					if(cnt2<=0){
						show("淫纹上的数字变成了0。")
						show("你感到子宫内有一种奇妙的感觉。")
						show("你意识到自己无法抗拒，也不必抗拒。")
						show("你躺倒在地，任凭快感传遍全身上下，体内体外的每一个位置。")
						show("粉色的光芒笼罩了你，你抵达了前所未有的强烈高潮。")
						show("当光芒散去时，你成为了魅魔。")
						show("结局：魔王的部下")
						gameover=true
						return
					}else{
						show("淫纹上的数字变成了"+cnt2+"。")
					}
				}
			}
			show("",true)
			show("“最后是穴天王，她可是四大天王里最为淫乱的一个……等等，穴天王人呢？”")
			show("另一个声音给了她答复：“前一段时间，穴天王说她好不容易才找到的顶级肉棒被冒险者毁了。现在，她踏上了寻找肉棒的新旅途。”")
			show("你好像在哪里听过这句话。",true)
			show("过了一会儿，魔王的声音再次响起：“按照惯例，这个位置应当属于魔王军当中最为淫乱的成员。那么……现在满足这个要求的人选是谁来着？”")
			show("另一个声音低声说了什么。")
			show("“有意思。”魔王评论道。")
			show("",true)
			show("新任的穴天王出现了。")
			show("“魔王命令我用这个和你战斗。我没法拒绝……”穴天王，也就是魅魔化的会长拿出了一根粗大的双头阳具，用口水做着润滑。",true)
			show("“这里就交给我吧！”教官脱下裤子，露出自己早已勃起的肉棒。")
			show("“没用没用……只不过是人类短小的鸡鸡，我一点感觉都不会有。”")
			show("“不试试看怎么知道呢？”教官挺腰攻向会长带着魔性魅力的肉穴。",true)
			show("插入之后没动几下，教官就射了出来。")
			show("但他没有放弃，保持着坚挺的状态，继续动着腰。")
			show("你知道教官不是会长的对手，只能希望会长看在多年的交情上少榨一点。")
			show("",true)
			show("在同伴做出了壮烈的牺牲后，你总算是来到了王座前。")
			show("“居然能做到这种程度，就让我称赞你一下吧。”魔王说道，“但是，你也就到此为止了。”")
			var hp=4
			show("“按照魔王的惯例，这时候应该说一些‘成为我的人吧’之类的话，但是，既然你已经注定要成为我的人了。再说这种话也没什么意思。”")
			show("魔王剩余生命值："+hp,true)
			show("“按照冒险者的惯例，看到血条就可以进攻了。”你回答道。",true)
			while(hp>0){
				var ans=check("max",succubus_pow+10)
				if(ans>=10){
					show("你的攻击命中了魔王的要害，魔王受到重创。")
					hp-=2
				}else if(ans>=0){
					show("你的攻击命中了魔王。")
					hp-=1
				}else{
					show("你的攻击被魔王躲开了。")
				}
				show("魔王剩余生命值："+hp)
				pause()
				if(hp>0){
					var a2=rand(3)
					if(a2==0){
						show("魔王看了你一眼，你的子宫内立刻就产生了反应。")
						gain({orgasm:rand(10)+1})
					}else if(a2==1){
						show("魔王接近了你的身体，用指尖轻轻触碰你的下腹。快感随着淫魔的魔力涌入你的身体。")
						gain({orgasm:rand(10)+10})
					}else{
						show("你躲开了魔王的攻击。")
					}
					if(a2!=2){
						var cnt2=cnt-status.orgasm
						if(cnt2<=0){
							show("淫纹上的数字变成了0。")
							show("你感到子宫内有一种奇妙的感觉。")
							show("你意识到自己无法抗拒，也不必抗拒。")
							show("你躺倒在地，任凭快感传遍全身上下，体内体外的每一个位置。")
							show("粉色的光芒笼罩了你，你抵达了前所未有的强烈高潮。")
							show("当光芒散去时，你成为了魅魔。",true)
							show("你被命令舔舐魔王的阴户。")							
							show("每当她的蜜汁流入你的嘴，你身上的淫魔之力就强化了一分。",true)
							show("会长出现了。")
							show("看着她不停滴落精液的下身，你知道冒险者们已经彻底失败了。")
							show("魔王的腿夹住你的头，催促你继续舔下去。")
							show("",true)
							if(hp<=2 &&"会长的同好"in buff){
								op["会长"].val+=10000
								show("她表示要向魔王献上自己的战利品。")
								show("获得魔王的准许后，她突然坐在了魔王的脸上：“请允许我奉上：敌人的精液。”")
								show("魔王被她压制，一时无法用言语命令你们。",true)
								show("你意识到这是个机会，猛烈地攻击着魔王的阴蒂。而会长维持着颜面骑乘的姿势继续摩擦着。")
								show("你和会长一上一下地责备着魔王，直到她浑身抽搐，失去了意识。")
								gainop("会长")
								show("",true)
								show("你们架空了魔王，颁布了停止袭击人类，由魅魔族负责处理全体魔物性欲的新政。")
								show("作为新晋的魅魔首领，你们以身作则地投入到了对异种族的慰问工作当中，过上了无比充实的生活。",true)
								show("结局：魅魔的下克上")
								gameover=true
								return
							}
							show("几个月后，你作为魔王军的先锋，向着人类的国度发起进攻。")
							show("所到之后尽是一片淫靡景象。",true)
							show("结局：魔王的先锋")
							gameover=true
							return
						}else{
							show("淫纹上的数字变成了"+cnt2+"。")
						}
					}
				}
			}
			
			show("终于，魔王倒下了。")
			show("“哥哥一定会替我报仇的……”她留下了不妙的台词，亦或是续作的线索。")
			show("淫纹上的数字停止了跳动。")
			op["会长"].val+=10000

			pause()
			show("")
			var max_op=5
			chapter=6
			if("纹身：娼妇" in buff){
				show("你们尝试了各种手段，也没能让会长从魅魔变回人类。")
				show("会长和教官决定去向遥远国度的贤者寻求帮助，他们一同踏上了旅途。",true)
				show("由于讨伐魔王的功绩，公会会长的位置被传给了你。")
				show("你拒绝了冒险者公会的烂摊子，表示自己还有更重要的事情要做。",true)
				show("你专注于娼馆中的工作。")
				show("某一天，客人认出了你是讨伐魔王的女勇者。")
				show("正当你不知道该怎么回应时，娼馆老板替你做出了解释：“这是本店新推出的角色扮演服务，欢迎想要凌辱女勇者的客人尝试。”")
				show("“至于她啊，只是个扮成女勇者的婊子。”")
				show("你觉得这个解释再好不过了。",true)
				show("结局：娼馆里的女勇者")
				gameover=true
				return
			}
			if("武道家的战友"in buff && getop("武道家")>max_op)max_op=getop("武道家")
			if("魔法师的恋人"in buff && getop("魔法师")>max_op)max_op=getop("魔法师")
			if("刺客的密友"in buff && getop("刺客")>max_op)max_op=getop("刺客")
			if(status.v_virgin==""){
				show("你们尝试了各种手段，也没能让会长从魅魔变回人类。")
				show("会长和教官决定去向遥远国度的贤者寻求帮助，他们一同踏上了旅途。",true)
				show("由于讨伐魔王的功绩，公会会长的位置被传给了你。")
				show("你接下了冒险者公会的烂摊子，忙得焦头烂额。",true)
				show("但冒险经历已经改变了你的身体。你时不时会……")
				show("等一下……你居然还是处女，这怎么可能？")
				show("你怎么可能从这么多随机事件当中幸免？",true)
				show("结局：天命之子或者风灵月影")
				gameover=true
				return
			}
			if(max_op==getop("武道家")){
				show("你们尝试了各种手段，也没能让会长从魅魔变回人类。")
				show("会长和教官决定去向遥远国度的贤者寻求帮助，他们一同踏上了旅途。",true)
				show("由于讨伐魔王的功绩，公会会长的位置被传给了你。")
				show("你接下了冒险者公会的烂摊子，忙得焦头烂额。",true)
				show("为了分担你的压力，武道家接替了教官的位置。")
				show("你们在职场上的配合就像在战场上一样默契。",true)
				show("结局：武道家的战友")
				gameover=true
				return
			}
			if(max_op==getop("魔法师")){
				show("你们尝试了各种手段，也没能让会长从魅魔变回人类。")
				show("会长和教官决定去向遥远国度的贤者寻求帮助，他们一同踏上了旅途。",true)
				show("由于讨伐魔王的功绩，公会会长的位置被传给了你。")
				show("你接下了冒险者公会的烂摊子，忙得焦头烂额。",true)
				show("在结束一天忙碌的工作后，你回到家中。")
				show("“你要先吃饭，先洗澡，还是先吃我呢？”魔法师一如既往地问道。")
				show("结局：魔法师的恋人")
				gameover=true
				return
			}
			if(max_op==getop("刺客")){
				show("你们尝试了各种手段，也没能让会长从魅魔变回人类。")
				show("会长和教官决定去向遥远国度的贤者寻求帮助，他们一同踏上了旅途。",true)
				show("由于讨伐魔王的功绩，公会会长的位置被传给了你。")
				show("你拒绝了冒险者公会的烂摊子，表示自己也要向遥远国度的贤者寻求帮助，治疗刺客的扶她诅咒。",true)
				show("在那之后的某一天，你带着面色潮红的刺客进了旅馆，准备为她处理性欲。")
				show("恰巧你碰到神清气爽的会长和委顿不堪的教官从旅馆了走了出来。")
				show("你们露出了心照不宣的笑容。",true)
				show("结局：刺客的密友")
				gameover=true
				return
			}
			show("你们尝试了各种手段，也没能让会长从魅魔变回人类。")
			show("会长和教官决定去向遥远国度的贤者寻求帮助，他们一同踏上了旅途。",true)
			show("由于讨伐魔王的功绩，公会会长的位置被传给了你。")
			show("你接下了冒险者公会的烂摊子，忙得焦头烂额。",true)
			show("但冒险经历已经改变了你的身体。你时不时会消失几天，外出释放一下性欲。")
			show("每当你抵达高潮时，下腹的淫纹都会产生微弱的魔力反应——这是个危险的信号，但你已经离不开这样的生活了。")
			show("或许有一天你的淫纹会再次亮起光芒，到时候会有新的英雄拯救世界吗？或者，就此堕落也不失为一个快乐的结局？")
			show("结局：会长的继承者")
			gameover=true
			return
		},
		town:false,
		once:true,
		chance:function(){
			if(past_event.includes("guild_succubus3"))
				return 10000
		},
		start:5,
		end:5
	}
}