function town_basic(){
	ev["wind"]={
		ev:function(){
			show("一阵大风吹过，你的裙底风光暴露在人前。")
			if(no_pant()){
				show("至少没有人看见你的内裤。")
				show("当你没穿内裤的下体被路人一览无余时，你乐观地想着。")
				gain({e_exp:2})
			}else{
				show("人们看见了你的内裤。")
				gain({e_exp:1})
			}
		},
		town:true,
		chance:function(){
			return 0.5
		}
	}
	ev["stolen_underwear"]={
		ev:function(){
			show("你的内裤被人偷走了。")
			gain({money:-5})
			gainflag("lost_underwear",1)
			if(status.lewd>=20){
				show("你幻想着内衣小偷要用你的贴身衣物去做什么，下体不禁有些湿润。")
				gain({lust:2})
			}
		},
		town:true,
		chance:function(){
			return 0.3
		}
	}
	ev["girls_talk"]={
		ev:function(){
			show("你听到几个女冒险者在小声谈论被哪种魔物侵犯更加舒服。")
			show("你向她们分享了你的理解。她们对你肃然起敬。")
			gain({lust:2})
		},
		town:true,
		once:true,
		chance:function(){
			if(status.lewd>=20)return 0.3
		},
		start:2
	}
	ev["bad"]={
		ev:function(){
			show("你在浴场洗澡时被偷窥了。")
			gain({e_exp:2})
			if(check("wis",month+12)>=0){
				show("你抓住偷窥者，交给了自警团。")
				gain({money:50})
				gainflag("bad")
			}
		},
		town:true,
		chance:function(){
			if(!("bad"in flag))return 0.2
		}
	}
	ev["bad2"]={
		ev:function(){
			show("你在市场拥挤的人群中遇到了痴汉。")
			if(check("dex",month+14)>=0){
				gain({a_exp:1})
				show("你抓住痴汉，交给了自警团。")
				gain({money:50})
				gainflag("bad2")
			}else{
				show("痴汉玩弄着你的屁股，你捂住嘴避免发出声音。")
				gain({a_exp:2})
			}
		},
		town:true,
		chance:function(){
			if(!("bad2"in flag))return 0.15
		},
		start:2
	}
	ev["bad3"]={
		ev:function(){
			show("你在夜晚的街道上被强奸魔袭击了。")
			if(check("str",month+16)>=0){
				show("你打倒了强奸魔，交给了自警团。")
				gain({money:50})
				gainflag("bad3")
			}else{
				show("强奸魔在你的体内射了一发后，满足地离去。")
				gain({v_exp:5,s_exp:1,p_exp:2})
			}
		},
		town:true,
		chance:function(){
			if(!("bad3"in flag))return 0.1
		},
		start:3
	}
	ev["bad4"]={
		ev:function(){
			if(check("wis",month+18)>=0){
				show("你察觉到有人在你的酒里下了药。")
				show("你假装昏迷，几个曾经被你送进自警团的流氓朝你靠了过来。")
				show("你当场发作，再次将他们送进了自警团。")
				gain({money:100})
			}else{
				show("你被人在酒里下了药。")
				show("在下身的痛觉中，你醒了过来。")
				show("强奸魔告诉你，这是对你将流氓送进自警团的报复。")
				gain({v_exp:9,a_exp:3,o_exp:3,s_exp:4,p_exp:5})
				pause()
				show("事后他们脱光了你的衣服，将你锁在一间破旧的男厕所里。")
				gainbuff("公共厕所",1)
			}
		},
		town:true,
		once:true,
		chance:function(){
			if(("bad"in flag)&&("bad2"in flag)&&("bad3"in flag))return 0.2
		},
		//start:4
	}
	ev["toilet"]={
		ev:function(){
			ans=rand(4)
			show("你的身体被固定在墙内，上半身和下半身朝向不同的厕所隔间，作为便器提供一枚铜币一次的服务。")
			if(ans==2){
				gain({v_exp:8,a_exp:4,o_exp:6,s_exp:6,u_exp:2,e_exp:5},"路人")
				show("",true)
				show("教官来到这间厕所，将你放了出来。")
				show("没有人敢阻拦他。")
				gainbuff("公共厕所",-10000)
				return
			}else if(ans==3 && "契约：娼妇"in buff){
				gain({v_exp:8,a_exp:4,o_exp:6,s_exp:6,u_exp:2,e_exp:5},"路人")
				show("",true)
				show("娼馆老板带着几个打手将你从厕所中解救出来。")
				show("“我店里的商品可不能只卖这么点钱。”老板说道。")
				gainbuff("公共厕所",-10000)
				return
			}else if(ans==0 && getbuff("公共厕所")>=4){
				show("随着使用人数的增加，你的身体变得越来越肮脏。")
				show("最终，连流浪汉都不想使用你了。",true)
				show("你知道失去利用价值的肉便器会是什么下场，不得不出声恳求路过的男人使用自己。")
				show("男人考虑了一下之后说：“便器就该干便器该干的事。”")
				show("他命令你张开嘴，然后对着里面撒了一泡尿。")
				show("")
				show("结局：肉便器的末路")
				gameover=true
				return
			}else{
				ans2=rand(4)
				gain({v_exp:8,a_exp:4,o_exp:6,s_exp:6,u_exp:2,e_exp:5},"路人")
			}
			gainbuff("公共厕所",1)
		},
		town:true,
		chance:function(){
			if("公共厕所"in buff)return 10000
		}
	}
	ev["toilet2"]={
		ev:function(){
			ans=rand(4)
			show("你的身体被固定在墙内，上半身和下半身朝向不同的厕所隔间，作为便器提供一枚铜币一次的服务。")
			if(ans==2){
				gain({v_exp:8,a_exp:4,o_exp:6,s_exp:6,u_exp:2,e_exp:5},"路人")
				show("",true)
				show("教官来到这间厕所，将你放了出来。")
				show("没有人敢阻拦他。")
				gainbuff("公共厕所",-10000)
				return
			}else if(ans==3 && "契约：娼妇"in buff){
				gain({v_exp:8,a_exp:4,o_exp:6,s_exp:6,u_exp:2,e_exp:5},"路人")
				show("",true)
				show("娼馆老板带着几个打手将你从厕所中解救出来。")
				show("“我店里的商品可不能只卖这么点钱。”老板说道。")
				gainbuff("公共厕所",-10000)
				return
			}else if(ans==0 && getbuff("公共厕所")>=4){
				show("随着使用人数的增加，你的身体变得越来越肮脏。")
				show("最终，连流浪汉都不想使用你了。",true)
				show("你知道失去利用价值的肉便器会是什么下场，不得不出声恳求路过的男人使用自己。")
				show("男人考虑了一下之后说：“便器就该干便器该干的事。”")
				show("他命令你张开嘴，然后对着里面撒了一泡尿。")
				show("")
				show("结局：肉便器的末路")
				gameover=true
				return
			}else{
				ans2=rand(4)
				gain({v_exp:8,a_exp:4,o_exp:6,s_exp:6,u_exp:2,e_exp:5},"路人")
			}
			gainbuff("公共厕所",1)
		},
		town:false,
		chance:function(){
			if("公共厕所"in buff)return 10000
		}
	}
	ev["exhibition"]={
		ev:function(){
			show("你在夜晚的街道上露出。")
			gain({e_exp:2})
			pause()
			if(check("dex",status.lewd)>=0){
				if(status.e_lv>=5){
					show("你遇见了几个过路人，毫不在意地继续展示着你的身体。")
					gain({e_exp:5})					
				}else{
					show("你遇见了几个过路人，连忙逃跑了。")
					gain({e_exp:3})
				}
			}else{
				show("你遇见了几个过路人，他们将你包围了。")
				show("你被迫为他们提供了口交侍奉。")
				gain({e_exp:3,o_exp:5,s_exp:2,b_exp:2},"路人")
			}
		},
		town:true,
		once:false,
		chance:function(){
			if(status.e_lv>=3) return 0.5
		}
	}
	ev["cost"]={
		ev:function(){
			show("商队被打劫了，导致城内物价上涨。")
			show("等到商路恢复畅通后，物价却没有降回去的意思。")
			gain({pay:50})
		},
		town:true,
		once:true,
		chance:function(){
			return 0.5
		},
		start:2
	}
	ev["cost2"]={
		ev:function(){
			show("随着朋友数量的增加，交际费用也随之增长。")
			gain({pay:50})
		},
		town:true,
		once:true,
		chance:function(){
			if(getop("武道家")>0&&getop("魔法师")>0&&getop("刺客")>0)return 0.5
		},
	}
	ev["cost3"]={
		ev:function(){
			show("越到后期，旅馆越贵。")
			show("这可是剑与魔法世界的常识。")
			gain({pay:100})
		},
		town:true,
		once:true,
		chance:function(){
			return 0.5
		},
		start:4
	}
	ev["masturbation"]={
		ev:function(){
			if("露宿街头" in buff || status.e_lv>=3){
				show("你在公园的无人处自慰。")
				masturbation(Math.floor(status.lust/2)+3)
				pause()
				if(rand(8)+status.m_lv>=8){
					show("路过的男人发现了你。")
					show("你毫无抵抗地被侵犯了。")
					gain({v_exp:3,s_exp:1,e_exp:3},"路人")
				}else{
					show("你强忍着快感，没有发出声音。")
				}
			}else{
				show("你在旅馆的房间中自慰。")
				masturbation(Math.floor(status.lust/2)+3)
			}
		},
		town:true,
		once:true,
		chance:function(){
			if(status.lust>=3) return 0.7
		}
	}
	ev["masturbation2"]={
		ev:function(){
			show("你在地下城的无人处自慰。")
			masturbation(Math.floor(status.lust/2)+3)
			pause()
			if(rand(6)+status.m_lv>=6){
				ans=rand(4)
				if(ans==0){
					show("路过的男冒险者发现了你。")
					show("你毫无抵抗地被侵犯了。")
					gain({v_exp:3,s_exp:1,e_exp:3},"冒险者")
				}else if(ans==1){
					show("路过的女冒险者发现了你。")
					show("她一脸鄙夷地看着你高潮的样子。")
					gain({e_exp:3,les_exp:1})
				}else{
					if(chapter==1){
						show("路过的哥布林发现了你。")
						show("你毫无抵抗地被侵犯了。")
						gain({v_exp:3,s_exp:1},"哥布林")
					}
					if(chapter==2){
						show("路过的史莱姆发现了你。")
						show("你毫无抵抗地被侵犯了——然后又因为史莱姆身上的催情粘液再自慰了一次。")
						gain({v_exp:5,m_exp:2,s_exp:1},"史莱姆")
					}
					if(chapter==3){
						show("路过的兽人发现了你。")
						show("你毫无抵抗地被侵犯了。")
						gain({v_exp:5,p_exp:2,s_exp:1},"兽人")
					}
					if(chapter==4){
						show("路过的触手发现了你。")
						show("你毫无抵抗地被侵犯了。")
						gain({v_exp:3,a_exp:3,s_exp:2},"触手")
					}
					if(chapter==5){
						show("路过的魅魔发现了你。")
						show("她看着你高潮的样子点了点头，然后表示要陪着你一起自慰。")
						gain({v_exp:3,m_exp:3,e_exp:3,les_exp:3})
					}
				}
			}else{
				show("你强忍着快感，没有发出声音。")
			}
		},
		town:false,
		once:false,
		chance:function(){
			if(status.lust>=5) return 0.5
		}
	}
}

function no_pant(){
	return(check("e_lv",5,5)>=0)
}

function masturbation(n){
	ans=rand(3)
	if(ans==0 && status.a_lv>=2){
		show("你将手指伸进肛门，体会着禁忌的快感。")
		gain({a_exp:n,m_exp:n})
	}else if(ans==1){
		show("你将手指伸进阴道，刺激着内部。")
		gain({v_exp:n,m_exp:n})
		if(status.v_lv>=3){
			show("你需要更粗的东西——你决定将自己的武器当做自慰棒使用。")
			gain({v_exp:n,m_exp:n,p_exp:n},"你")
		}
	}else{
		show("你玩弄着敏感的乳头和阴蒂。")
		gain({b_exp:Math.floor(n/2),v_exp:Math.floor(n/2),m_exp:n})
	}
	status.lust=0
}